//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Art_Gallery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int ReviewId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> ArtworkId { get; set; }
        public string Reviews { get; set; }
    
        public virtual Artwork Artwork { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
